poverty-plots: plots.r poverty.r
	Rscript -e "require(RCurl); \
	  require(devtools); \
	  source_url('https://raw.github.com/wesesque/gwr/master/code/poverty/poverty.r'); \
	  source_url('https://raw.github.com/wesesque/gwr/master/code/poverty/plots.r'); \
	  source_url('https://raw.github.com/wesesque/gwr/master/code/practice-talk/poverty-plots.r');"
