future.pdf: future.md
	pandoc -N --template=mytemplate.tex --variable mainfont=Georgia --variable sansfont=Arial  --variable fontsize=12pt --variable version=1.11 future.md --latex-engine=xelatex --toc -o future.pdf


